<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mridul_profile-icon</name>
   <tag></tag>
   <elementGuidId>81a8aa69-bc5d-4ecc-8610-570b5932af38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appMountPoint']/div/div/div/div/div/div/div[2]/div/div/ul/li[2]/div/a/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Esha&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53373324-f6f0-4c22-9194-1fd67407f31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile-icon</value>
      <webElementGuid>69e08b36-1b89-4e6e-9cb5-27a1e8b0d081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-profile-guid</name>
      <type>Main</type>
      <value>VVZTOP7ZWZAMJNLXVP6ZXA7U74</value>
      <webElementGuid>d7e05b9a-3445-4bf3-814e-d216aa2a659d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appMountPoint&quot;)/div[1]/div[@class=&quot;netflix-sans-font-loaded&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;bd dark-background&quot;]/div[@class=&quot;profiles-gate-container&quot;]/div[@class=&quot;centered-div list-profiles-container&quot;]/div[@class=&quot;list-profiles&quot;]/ul[@class=&quot;choose-profile&quot;]/li[@class=&quot;profile&quot;]/div[1]/a[@class=&quot;profile-link&quot;]/div[@class=&quot;avatar-wrapper&quot;]/div[@class=&quot;profile-icon&quot;]</value>
      <webElementGuid>91066f14-656b-4f47-99c7-163213e07c8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appMountPoint']/div/div/div/div/div/div/div[2]/div/div/ul/li[2]/div/a/div/div</value>
      <webElementGuid>33936f9e-2466-415e-8413-cb3a36849a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mridul'])[1]/following::div[4]</value>
      <webElementGuid>ca4f6895-dde1-4fa6-9b99-bb44f2019fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Esha'])[1]/preceding::div[1]</value>
      <webElementGuid>8339c580-2589-45f0-828c-0d3f6706a6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Children'])[1]/preceding::div[4]</value>
      <webElementGuid>7974f49b-0b62-4384-b33b-1a7445456222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a/div/div</value>
      <webElementGuid>10ca1dd7-0308-4538-9a25-3452a55cef01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
